// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025 germondai - https://github.com/germondai

// Serves /sitemap.xml as a sitemapindex pointing to /sitemap-0.xml (generated by @astrojs/sitemap).
// Both dev mode and production work without any special server config.

import type { APIContext } from 'astro'

export const prerender = true

export const GET = ({ site }: APIContext) => {
  const base = site ? site.href.replace(/\/$/, '') : ''
  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    `  <sitemap><loc>${base}/sitemap-0.xml</loc></sitemap>`,
    '</sitemapindex>',
  ].join('\n')
  return new Response(xml, { headers: { 'Content-Type': 'application/xml; charset=utf-8' } })
}
